[package]
name = "resource-game"
version = "0.1.0"
authors = ["Jarvis Carroll <spiveehere@gmail.com>"]
publish = false

[dependencies]
vulkano = "0.11"
vulkano-shaders = "0.11"
vulkano-win = "0.11"
winit = "0.18"
rand = "0.7"
